const quotes = [
    "O verdadeiro poder vem de dentro de você. - Naruto",
    "Se você não acredita em si mesmo, ninguém mais acreditará. - One Piece",
    "Aqueles que não arriscam nada não ganham nada. - Naruto",
    "Não importa o quão difícil seja, continue caminhando. - Attack on Titan",
    "Não importa o quanto você esteja perdido, sempre há algo que pode guiá-lo. - Fullmetal Alchemist",
    "As coisas que você pensa que não consegue fazer, podem ser feitas. - Hunter x Hunter",
    "Você é mais forte do que pensa. - Dragon Ball Z",
    "A vida não é sobre esperar a tempestade passar, é sobre aprender a dançar na chuva. - One Piece",
    "Você pode alcançar o impossível se nunca desistir. - Naruto",
    "Cada desafio é uma oportunidade para crescer. - My Hero Academia",
    "Se você der seu melhor, vai se arrepender de nada. - Bleach",
    "O fracasso é apenas um trampolim para o sucesso. - Attack on Titan",
    "Nunca desista dos seus sonhos, mesmo que seja difícil. - One Piece",
    "Os verdadeiros heróis são aqueles que protegem os outros. - My Hero Academia",
    "O destino não é algo que você deve aceitar. É algo que você deve conquistar. - Naruto",
    "Não importa o quanto você caia, sempre se levante. - Dragon Ball Z",
    "Você nunca sabe o que pode fazer até tentar. - Hunter x Hunter",
    "Se você lutar até o fim, você pode conquistar qualquer coisa. - Naruto",
    "A força de um homem não é medida pelo tamanho de seu corpo, mas pela força de seu espírito. - One Piece",
    "Cada derrota é uma lição que nos faz mais fortes. - Bleach",
    "Os amigos são a nossa verdadeira força. - One Piece",
    "A verdadeira luta é aquela contra os nossos próprios medos. - Naruto",
    "Sempre olhe para frente e nunca se arrependa. - Fullmetal Alchemist",
    "As dificuldades são apenas oportunidades disfarçadas. - Attack on Titan",
    "Você nunca sabe até onde pode ir, até tentar. - One Piece",
    "Lute pelo que você acredita e nunca desista. - Dragon Ball Z",
    "O mais importante é ter coragem e não se render. - My Hero Academia",
    "Sua vida é sua. Faça o melhor de cada momento. - Naruto",
    "Cada um tem o seu próprio ritmo. Não se compare com os outros. - Fruits Basket",
    "A esperança é o último sentimento que se perde. - Attack on Titan",
    "Quando tudo parece perdido, é quando você deve dar o seu melhor. - Bleach",
    "A dor é um sinal de que você está vivo. - One Piece",
    "A maior batalha é contra você mesmo. - Naruto",
    "Nunca é tarde para mudar. - Hunter x Hunter",
    "O importante não é o quanto você tem, mas o quanto você pode dar. - Fairy Tail",
    "A cada erro, você aprende algo novo. - Dragon Ball Z",
    "Se você não lutar por sua vida, quem o fará? - My Hero Academia",
    "A vida é curta, então viva com propósito. - One Piece",
    "O futuro é criado pelas escolhas que fazemos hoje. - Naruto",
    "Não deixe a dor definir quem você é. - Attack on Titan",
    "Mesmo que você caia, sempre se levante. - Bleach",
    "O que importa é o que você faz com o seu poder. - Fullmetal Alchemist",
    "A verdadeira força vem de dentro. - Hunter x Hunter",
    "Nunca desista, nunca se arrependa. - My Hero Academia",
    "O sucesso é conquistado por aqueles que não têm medo de falhar. - Naruto",
    "Seja mais forte do que seus medos. - One Piece",
    "Não importa o quão difícil seja o caminho, sempre siga em frente. - Dragon Ball Z",
    "Não importa quantas vezes você caia, o que importa é quantas vezes você se levanta. - Rocky Balboa, Rocky",
    "O que você faz hoje pode melhorar todos os seus amanhãs. - Ralph Waldo Emerson, Transformers",
    "O medo não é real. O que é real é a coragem. - Will Smith, Depois da Terra",
    "Você não precisa ser um herói para fazer a coisa certa. - Stan Lee, Spider-Man",
    "A coragem não é a ausência do medo, é a decisão de que algo é mais importante do que o medo. - Braveheart, Coração Valente",
    "Não importa o que aconteça, continue lutando. - Kratos, God of War",
    "A única maneira de fazer um excelente trabalho é amar o que você faz. - Steve Jobs, Jobs",
    "O poder vem de onde você não espera. - Yoda, Star Wars",
    "O que define um herói não é sua habilidade, mas sim sua vontade. - Stan Lee, X-Men",
    "Nunca subestime o poder da força. - Darth Vader, Star Wars",
    "Eu sou inevitável. - Thanos, Avengers: Endgame",
    "As cicatrizes nos ensinam que sobreviver vale a pena. - Steve Rogers, Captain America",
    "A maior vitória é a que vem do trabalho em equipe. - Han Solo, Star Wars",
    "Às vezes a única maneira de lutar é quebrando todas as regras. - Deadpool, Deadpool",
    "A maior batalha que você enfrentará é com você mesmo. - Kratos, God of War",
    "O caminho para a grandeza começa com um pequeno passo. - Bilbo Baggins, O Senhor dos Anéis",
    "O que importa não é quão grande você é, mas quão grande você se torna. - Superman, Man of Steel",
    "Não existe um 'não posso' quando se trata de alcançar seus sonhos. - Naruto Uzumaki, Naruto",
    "O impossível é só uma palavra, não uma barreira. - Captain Marvel, Captain Marvel",
    "Às vezes, a maior força está em ser gentil. - Spider-Man, Spider-Man: Into the Spider-Verse",
    "A vida nunca é fácil, mas é isso que faz ela valer a pena. - Ellie, The Last of Us",
    "Lembre-se: os heróis não nascem, eles se fazem. - Batman, The Dark Knight",
    "A perseverança é o caminho para a verdadeira grandeza. - Master Chief, Halo",
    "Você nunca sabe sua verdadeira força até ser testado. - Harry Potter, Harry Potter",
    "Nenhum obstáculo é grande demais quando você tem a vontade de superá-lo. - Katniss Everdeen, Jogos Vorazes",
    "Eu sou Groot. - Groot, Guardiões da Galáxia",
    "A vida é o que você faz dela. - The Doctor, Doctor Who",
    "O medo é o inimigo da coragem. Enfrente o medo, e a coragem será sua. - Arthur Curry, Aquaman",
    "Às vezes, você tem que fazer o que é certo, mesmo quando é difícil. - Iron Man, Avengers",
    "Você não precisa de superpoderes para ser um herói. - Spider-Man, Spider-Man: Homecoming",
    "A dor é temporária, mas a glória é eterna. - Wolverine, X-Men",
    "O único modo de não errar é não tentar. - Professor X, X-Men",
    "Sempre que o jogo parece perdido, o herói encontra uma maneira. - Gandalf, O Senhor dos Anéis",
    "Não existe falha, apenas feedback. - Neo, Matrix",
    "O maior inimigo não é aquele que você vê, mas o que está dentro de você. - Maximus, Gladiador",
    "O impossível é só uma questão de perspectiva. - Ezio Auditore, Assassin's Creed",
    "A única coisa que temos que temer é o medo em si. - Franklin D. Roosevelt, Watchmen",
    "Você tem o poder de fazer o bem. - Batman, The Dark Knight",
    "Nada é impossível para alguém que tem coragem de tentar. - Wonder Woman, Wonder Woman",
    "O universo é mais vasto do que você pode imaginar. Explore-o. - Spock, Star Trek",
    "Nunca se arrependa de ter dado tudo de si. - Lara Croft, Tomb Raider",
    "A verdadeira força vem da vulnerabilidade. - Elektra, Daredevil",
    "Não importa o quão escuro seja o caminho, sempre há uma luz. - The Doctor, Doctor Who",
    "O que você faz pode parecer pequeno, mas para alguém, pode ser tudo. - TChalla, Black Panther",
    "O destino não é algo que você deve aceitar, é algo que você pode criar. - Stark, Avengers",
    "O que importa é como você reage diante da adversidade. - Kratos, God of War",
    "Se você não tentar, nunca saberá do que é capaz. - Max Payne, Max Payne",
    "Você é capaz de mais do que imagina. - Dumbledore, Harry Potter",
    "Você pode sempre começar de novo. - Aloy, Horizon Zero Dawn",
    "Os maiores heróis são os que continuam lutando, mesmo quando todos dizem que não podem. - Luke Skywalker, Star Wars"

];

const quoteElement = document.getElementById("quote");
const newQuoteButton = document.getElementById("new-quote");

function getNewQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.textContent = quotes[randomIndex];
}

newQuoteButton.addEventListener("click", getNewQuote);
